/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.upstox.api.UnsettledProfit;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CashUnavailableToTrade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class CashUnavailableToTrade {
  @SerializedName("unsettled_profit")
  private UnsettledProfit unsettledProfit = null;

  public CashUnavailableToTrade unsettledProfit(UnsettledProfit unsettledProfit) {
    this.unsettledProfit = unsettledProfit;
    return this;
  }

   /**
   * Get unsettledProfit
   * @return unsettledProfit
  **/
  @Schema(description = "")
  public UnsettledProfit getUnsettledProfit() {
    return unsettledProfit;
  }

  public void setUnsettledProfit(UnsettledProfit unsettledProfit) {
    this.unsettledProfit = unsettledProfit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashUnavailableToTrade cashUnavailableToTrade = (CashUnavailableToTrade) o;
    return Objects.equals(this.unsettledProfit, cashUnavailableToTrade.unsettledProfit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unsettledProfit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashUnavailableToTrade {\n");
    
    sb.append("    unsettledProfit: ").append(toIndentedString(unsettledProfit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
