/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.upstox.api.DeliveryMargin;
import com.upstox.api.Loss;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CashMarginUsed
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class CashMarginUsed {
  @SerializedName("total")
  private Object total = null;

  @SerializedName("mtf")
  private Object mtf = null;

  @SerializedName("loss")
  private Loss loss = null;

  @SerializedName("span_exposure")
  private Object spanExposure = null;

  @SerializedName("cash_margin_var_elm")
  private Object cashMarginVarElm = null;

  @SerializedName("premium_present")
  private Object premiumPresent = null;

  @SerializedName("delivery_margin")
  private DeliveryMargin deliveryMargin = null;

  public CashMarginUsed total(Object total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(description = "")
  public Object getTotal() {
    return total;
  }

  public void setTotal(Object total) {
    this.total = total;
  }

  public CashMarginUsed mtf(Object mtf) {
    this.mtf = mtf;
    return this;
  }

   /**
   * Get mtf
   * @return mtf
  **/
  @Schema(description = "")
  public Object getMtf() {
    return mtf;
  }

  public void setMtf(Object mtf) {
    this.mtf = mtf;
  }

  public CashMarginUsed loss(Loss loss) {
    this.loss = loss;
    return this;
  }

   /**
   * Get loss
   * @return loss
  **/
  @Schema(description = "")
  public Loss getLoss() {
    return loss;
  }

  public void setLoss(Loss loss) {
    this.loss = loss;
  }

  public CashMarginUsed spanExposure(Object spanExposure) {
    this.spanExposure = spanExposure;
    return this;
  }

   /**
   * Get spanExposure
   * @return spanExposure
  **/
  @Schema(description = "")
  public Object getSpanExposure() {
    return spanExposure;
  }

  public void setSpanExposure(Object spanExposure) {
    this.spanExposure = spanExposure;
  }

  public CashMarginUsed cashMarginVarElm(Object cashMarginVarElm) {
    this.cashMarginVarElm = cashMarginVarElm;
    return this;
  }

   /**
   * Get cashMarginVarElm
   * @return cashMarginVarElm
  **/
  @Schema(description = "")
  public Object getCashMarginVarElm() {
    return cashMarginVarElm;
  }

  public void setCashMarginVarElm(Object cashMarginVarElm) {
    this.cashMarginVarElm = cashMarginVarElm;
  }

  public CashMarginUsed premiumPresent(Object premiumPresent) {
    this.premiumPresent = premiumPresent;
    return this;
  }

   /**
   * Get premiumPresent
   * @return premiumPresent
  **/
  @Schema(description = "")
  public Object getPremiumPresent() {
    return premiumPresent;
  }

  public void setPremiumPresent(Object premiumPresent) {
    this.premiumPresent = premiumPresent;
  }

  public CashMarginUsed deliveryMargin(DeliveryMargin deliveryMargin) {
    this.deliveryMargin = deliveryMargin;
    return this;
  }

   /**
   * Get deliveryMargin
   * @return deliveryMargin
  **/
  @Schema(description = "")
  public DeliveryMargin getDeliveryMargin() {
    return deliveryMargin;
  }

  public void setDeliveryMargin(DeliveryMargin deliveryMargin) {
    this.deliveryMargin = deliveryMargin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashMarginUsed cashMarginUsed = (CashMarginUsed) o;
    return Objects.equals(this.total, cashMarginUsed.total) &&
        Objects.equals(this.mtf, cashMarginUsed.mtf) &&
        Objects.equals(this.loss, cashMarginUsed.loss) &&
        Objects.equals(this.spanExposure, cashMarginUsed.spanExposure) &&
        Objects.equals(this.cashMarginVarElm, cashMarginUsed.cashMarginVarElm) &&
        Objects.equals(this.premiumPresent, cashMarginUsed.premiumPresent) &&
        Objects.equals(this.deliveryMargin, cashMarginUsed.deliveryMargin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, mtf, loss, spanExposure, cashMarginVarElm, premiumPresent, deliveryMargin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashMarginUsed {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    mtf: ").append(toIndentedString(mtf)).append("\n");
    sb.append("    loss: ").append(toIndentedString(loss)).append("\n");
    sb.append("    spanExposure: ").append(toIndentedString(spanExposure)).append("\n");
    sb.append("    cashMarginVarElm: ").append(toIndentedString(cashMarginVarElm)).append("\n");
    sb.append("    premiumPresent: ").append(toIndentedString(premiumPresent)).append("\n");
    sb.append("    deliveryMargin: ").append(toIndentedString(deliveryMargin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
