/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CorporateActionData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-12T09:02:57.145121+05:30[Asia/Kolkata]")

public class CorporateActionData {
  @SerializedName("name")
  private Object name = null;

  @SerializedName("expiry_date")
  private Object expiryDate = null;

  @SerializedName("amount")
  private Object amount = null;

  @SerializedName("ratio")
  private Object ratio = null;

  @SerializedName("event_details")
  private Object eventDetails = null;

   /**
   * Type of corporate action
   * @return name
  **/
  @Schema(example = "Dividend", description = "Type of corporate action")
  public Object getName() {
    return name;
  }

   /**
   * Ex-date or expiry date of the action
   * @return expiryDate
  **/
  @Schema(example = "14", description = "Ex-date or expiry date of the action")
  public Object getExpiryDate() {
    return expiryDate;
  }

   /**
   * Amount associated with the action
   * @return amount
  **/
  @Schema(example = "5.5", description = "Amount associated with the action")
  public Object getAmount() {
    return amount;
  }

   /**
   * Ratio for bonus or split actions
   * @return ratio
  **/
  @Schema(example = "2:10", description = "Ratio for bonus or split actions")
  public Object getRatio() {
    return ratio;
  }

   /**
   * Detailed event fields for the corporate action
   * @return eventDetails
  **/
  @Schema(description = "Detailed event fields for the corporate action")
  public Object getEventDetails() {
    return eventDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorporateActionData corporateActionData = (CorporateActionData) o;
    return Objects.equals(this.name, corporateActionData.name) &&
        Objects.equals(this.expiryDate, corporateActionData.expiryDate) &&
        Objects.equals(this.amount, corporateActionData.amount) &&
        Objects.equals(this.ratio, corporateActionData.ratio) &&
        Objects.equals(this.eventDetails, corporateActionData.eventDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, expiryDate, amount, ratio, eventDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorporateActionData {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    ratio: ").append(toIndentedString(ratio)).append("\n");
    sb.append("    eventDetails: ").append(toIndentedString(eventDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
