/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.upstox.api.MutualFundMetaData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * GetMutualFundOrdersResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-24T18:17:57.963741+05:30[Asia/Kolkata]")

public class GetMutualFundOrdersResponse {
  @SerializedName("status")
  private Object status = null;

  @SerializedName("data")
  private Object data = null;

  @SerializedName("meta_data")
  private MutualFundMetaData metaData = null;

  public GetMutualFundOrdersResponse status(Object status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }

  public GetMutualFundOrdersResponse data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * Mutual fund orders in the requested window.
   * @return data
  **/
  @Schema(description = "Mutual fund orders in the requested window.")
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }

  public GetMutualFundOrdersResponse metaData(MutualFundMetaData metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
   * Meta data for mutual fund orders
   * @return metaData
  **/
  @Schema(description = "Meta data for mutual fund orders")
  public MutualFundMetaData getMetaData() {
    return metaData;
  }

  public void setMetaData(MutualFundMetaData metaData) {
    this.metaData = metaData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMutualFundOrdersResponse getMutualFundOrdersResponse = (GetMutualFundOrdersResponse) o;
    return Objects.equals(this.status, getMutualFundOrdersResponse.status) &&
        Objects.equals(this.data, getMutualFundOrdersResponse.data) &&
        Objects.equals(this.metaData, getMutualFundOrdersResponse.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, data, metaData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMutualFundOrdersResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
