/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IncomeStatementData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-12T09:02:57.145121+05:30[Asia/Kolkata]")

public class IncomeStatementData {
  @SerializedName("type")
  private Object type = null;

  @SerializedName("time_period")
  private Object timePeriod = null;

  @SerializedName("units_in")
  private Object unitsIn = null;

  @SerializedName("income_statement")
  private Object incomeStatement = null;

  @SerializedName("full_statement")
  private Object fullStatement = null;

   /**
   * Report type: consolidated or standalone
   * @return type
  **/
  @Schema(example = "consolidated", description = "Report type: consolidated or standalone")
  public Object getType() {
    return type;
  }

   /**
   * Time period: yearly or quarterly
   * @return timePeriod
  **/
  @Schema(example = "yearly", description = "Time period: yearly or quarterly")
  public Object getTimePeriod() {
    return timePeriod;
  }

   /**
   * Unit of monetary values
   * @return unitsIn
  **/
  @Schema(example = "crore", description = "Unit of monetary values")
  public Object getUnitsIn() {
    return unitsIn;
  }

   /**
   * Income statement entries grouped by type (Revenue, Operating profit, Net profit)
   * @return incomeStatement
  **/
  @Schema(description = "Income statement entries grouped by type (Revenue, Operating profit, Net profit)")
  public Object getIncomeStatement() {
    return incomeStatement;
  }

   /**
   * List of financial statement income statement items with historical values
   * @return fullStatement
  **/
  @Schema(description = "List of financial statement income statement items with historical values")
  public Object getFullStatement() {
    return fullStatement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IncomeStatementData incomeStatementData = (IncomeStatementData) o;
    return Objects.equals(this.type, incomeStatementData.type) &&
        Objects.equals(this.timePeriod, incomeStatementData.timePeriod) &&
        Objects.equals(this.unitsIn, incomeStatementData.unitsIn) &&
        Objects.equals(this.incomeStatement, incomeStatementData.incomeStatement) &&
        Objects.equals(this.fullStatement, incomeStatementData.fullStatement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, timePeriod, unitsIn, incomeStatement, fullStatement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IncomeStatementData {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    timePeriod: ").append(toIndentedString(timePeriod)).append("\n");
    sb.append("    unitsIn: ").append(toIndentedString(unitsIn)).append("\n");
    sb.append("    incomeStatement: ").append(toIndentedString(incomeStatement)).append("\n");
    sb.append("    fullStatement: ").append(toIndentedString(fullStatement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
