/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Init token response data for indie user
 */
@Schema(description = "Init token response data for indie user")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T11:34:57.127899+05:30[Asia/Kolkata]")

public class IndieUserInitTokenData {
  @SerializedName("authorization_expiry")
  private String authorizationExpiry = null;

  @SerializedName("notifier_url")
  private String notifierUrl = null;

   /**
   * authorize token expiry
   * @return authorizationExpiry
  **/
  @Schema(example = "151064324", description = "authorize token expiry")
  public String getAuthorizationExpiry() {
    return authorizationExpiry;
  }

   /**
   * notifier webhook url
   * @return notifierUrl
  **/
  @Schema(example = "https://example.com", description = "notifier webhook url")
  public String getNotifierUrl() {
    return notifierUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndieUserInitTokenData indieUserInitTokenData = (IndieUserInitTokenData) o;
    return Objects.equals(this.authorizationExpiry, indieUserInitTokenData.authorizationExpiry) &&
        Objects.equals(this.notifierUrl, indieUserInitTokenData.notifierUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationExpiry, notifierUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndieUserInitTokenData {\n");
    
    sb.append("    authorizationExpiry: ").append(toIndentedString(authorizationExpiry)).append("\n");
    sb.append("    notifierUrl: ").append(toIndentedString(notifierUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
