/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IpoBidRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-08-17T18:30:36.248588+05:30[Asia/Kolkata]")

public class IpoBidRequest {
  @SerializedName("quantity")
  private Object quantity = null;

  @SerializedName("price")
  private Object price = null;

  public IpoBidRequest quantity(Object quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Number of shares bid for. Must be a multiple of the IPO&#x27;s &#x60;lot_size&#x60; and at least its &#x60;minimum_quantity&#x60;
   * @return quantity
  **/
  @Schema(example = "20", required = true, description = "Number of shares bid for. Must be a multiple of the IPO's `lot_size` and at least its `minimum_quantity`")
  public Object getQuantity() {
    return quantity;
  }

  public void setQuantity(Object quantity) {
    this.quantity = quantity;
  }

  public IpoBidRequest price(Object price) {
    this.price = price;
    return this;
  }

   /**
   * Bid price per share, in whole rupees — decimals are not accepted. Must sit within the IPO&#x27;s price band, or equal its &#x60;cut_off_price&#x60;
   * @return price
  **/
  @Schema(example = "850", required = true, description = "Bid price per share, in whole rupees — decimals are not accepted. Must sit within the IPO's price band, or equal its `cut_off_price`")
  public Object getPrice() {
    return price;
  }

  public void setPrice(Object price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpoBidRequest ipoBidRequest = (IpoBidRequest) o;
    return Objects.equals(this.quantity, ipoBidRequest.quantity) &&
        Objects.equals(this.price, ipoBidRequest.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpoBidRequest {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
