/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IpoOrderBid
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-08-17T18:30:36.248588+05:30[Asia/Kolkata]")

public class IpoOrderBid {
  @SerializedName("quantity")
  private Object quantity = null;

  @SerializedName("price")
  private Object price = null;

  @SerializedName("amount")
  private Object amount = null;

  @SerializedName("message")
  private Object message = null;

  public IpoOrderBid quantity(Object quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Number of shares bid for
   * @return quantity
  **/
  @Schema(example = "30", description = "Number of shares bid for")
  public Object getQuantity() {
    return quantity;
  }

  public void setQuantity(Object quantity) {
    this.quantity = quantity;
  }

  public IpoOrderBid price(Object price) {
    this.price = price;
    return this;
  }

   /**
   * Bid price per share
   * @return price
  **/
  @Schema(example = "150.3", description = "Bid price per share")
  public Object getPrice() {
    return price;
  }

  public void setPrice(Object price) {
    this.price = price;
  }

  public IpoOrderBid amount(Object amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Value of the bid, quantity x price
   * @return amount
  **/
  @Schema(example = "4509.0", description = "Value of the bid, quantity x price")
  public Object getAmount() {
    return amount;
  }

  public void setAmount(Object amount) {
    this.amount = amount;
  }

  public IpoOrderBid message(Object message) {
    this.message = message;
    return this;
  }

   /**
   * Message from the exchange for this bid, when one was returned
   * @return message
  **/
  @Schema(example = "Bid accepted", description = "Message from the exchange for this bid, when one was returned")
  public Object getMessage() {
    return message;
  }

  public void setMessage(Object message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpoOrderBid ipoOrderBid = (IpoOrderBid) o;
    return Objects.equals(this.quantity, ipoOrderBid.quantity) &&
        Objects.equals(this.price, ipoOrderBid.price) &&
        Objects.equals(this.amount, ipoOrderBid.amount) &&
        Objects.equals(this.message, ipoOrderBid.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, price, amount, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpoOrderBid {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
