/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IpoRegistrarInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-06-25T20:07:12.239739+05:30[Asia/Kolkata]")

public class IpoRegistrarInfo {
  @SerializedName("name")
  private Object name = null;

  @SerializedName("email")
  private Object email = null;

  @SerializedName("contact_name")
  private Object contactName = null;

  @SerializedName("contact_number")
  private Object contactNumber = null;

  @SerializedName("website")
  private Object website = null;

  @SerializedName("registrar")
  private Object registrar = null;

  public IpoRegistrarInfo name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public IpoRegistrarInfo email(Object email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public Object getEmail() {
    return email;
  }

  public void setEmail(Object email) {
    this.email = email;
  }

  public IpoRegistrarInfo contactName(Object contactName) {
    this.contactName = contactName;
    return this;
  }

   /**
   * Get contactName
   * @return contactName
  **/
  @Schema(description = "")
  public Object getContactName() {
    return contactName;
  }

  public void setContactName(Object contactName) {
    this.contactName = contactName;
  }

  public IpoRegistrarInfo contactNumber(Object contactNumber) {
    this.contactNumber = contactNumber;
    return this;
  }

   /**
   * Get contactNumber
   * @return contactNumber
  **/
  @Schema(description = "")
  public Object getContactNumber() {
    return contactNumber;
  }

  public void setContactNumber(Object contactNumber) {
    this.contactNumber = contactNumber;
  }

  public IpoRegistrarInfo website(Object website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @Schema(description = "")
  public Object getWebsite() {
    return website;
  }

  public void setWebsite(Object website) {
    this.website = website;
  }

  public IpoRegistrarInfo registrar(Object registrar) {
    this.registrar = registrar;
    return this;
  }

   /**
   * Get registrar
   * @return registrar
  **/
  @Schema(description = "")
  public Object getRegistrar() {
    return registrar;
  }

  public void setRegistrar(Object registrar) {
    this.registrar = registrar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpoRegistrarInfo ipoRegistrarInfo = (IpoRegistrarInfo) o;
    return Objects.equals(this.name, ipoRegistrarInfo.name) &&
        Objects.equals(this.email, ipoRegistrarInfo.email) &&
        Objects.equals(this.contactName, ipoRegistrarInfo.contactName) &&
        Objects.equals(this.contactNumber, ipoRegistrarInfo.contactNumber) &&
        Objects.equals(this.website, ipoRegistrarInfo.website) &&
        Objects.equals(this.registrar, ipoRegistrarInfo.registrar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, contactName, contactNumber, website, registrar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpoRegistrarInfo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    contactNumber: ").append(toIndentedString(contactNumber)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    registrar: ").append(toIndentedString(registrar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
