/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * KeyRatioData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-12T09:02:57.145121+05:30[Asia/Kolkata]")

public class KeyRatioData {
  @SerializedName("name")
  private Object name = null;

  @SerializedName("company_value")
  private Object companyValue = null;

  @SerializedName("sector_value")
  private Object sectorValue = null;

   /**
   * Name of the ratio
   * @return name
  **/
  @Schema(example = "P/E", description = "Name of the ratio")
  public Object getName() {
    return name;
  }

   /**
   * Ratio value for the company
   * @return companyValue
  **/
  @Schema(example = "20.15", description = "Ratio value for the company")
  public Object getCompanyValue() {
    return companyValue;
  }

   /**
   * Ratio value for the sector reference
   * @return sectorValue
  **/
  @Schema(example = "12.46", description = "Ratio value for the sector reference")
  public Object getSectorValue() {
    return sectorValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyRatioData keyRatioData = (KeyRatioData) o;
    return Objects.equals(this.name, keyRatioData.name) &&
        Objects.equals(this.companyValue, keyRatioData.companyValue) &&
        Objects.equals(this.sectorValue, keyRatioData.sectorValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, companyValue, sectorValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyRatioData {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    companyValue: ").append(toIndentedString(companyValue)).append("\n");
    sb.append("    sectorValue: ").append(toIndentedString(sectorValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
