/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * KillSwitchSegmentData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class KillSwitchSegmentData {
  @SerializedName("segment")
  private Object segment = null;

  @SerializedName("segment_status")
  private Object segmentStatus = null;

  @SerializedName("kill_switch_enabled")
  private Object killSwitchEnabled = null;

  public KillSwitchSegmentData segment(Object segment) {
    this.segment = segment;
    return this;
  }

   /**
   * Get segment
   * @return segment
  **/
  @Schema(description = "")
  public Object getSegment() {
    return segment;
  }

  public void setSegment(Object segment) {
    this.segment = segment;
  }

  public KillSwitchSegmentData segmentStatus(Object segmentStatus) {
    this.segmentStatus = segmentStatus;
    return this;
  }

   /**
   * Get segmentStatus
   * @return segmentStatus
  **/
  @Schema(description = "")
  public Object getSegmentStatus() {
    return segmentStatus;
  }

  public void setSegmentStatus(Object segmentStatus) {
    this.segmentStatus = segmentStatus;
  }

  public KillSwitchSegmentData killSwitchEnabled(Object killSwitchEnabled) {
    this.killSwitchEnabled = killSwitchEnabled;
    return this;
  }

   /**
   * Get killSwitchEnabled
   * @return killSwitchEnabled
  **/
  @Schema(description = "")
  public Object getKillSwitchEnabled() {
    return killSwitchEnabled;
  }

  public void setKillSwitchEnabled(Object killSwitchEnabled) {
    this.killSwitchEnabled = killSwitchEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KillSwitchSegmentData killSwitchSegmentData = (KillSwitchSegmentData) o;
    return Objects.equals(this.segment, killSwitchSegmentData.segment) &&
        Objects.equals(this.segmentStatus, killSwitchSegmentData.segmentStatus) &&
        Objects.equals(this.killSwitchEnabled, killSwitchSegmentData.killSwitchEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(segment, segmentStatus, killSwitchEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KillSwitchSegmentData {\n");
    
    sb.append("    segment: ").append(toIndentedString(segment)).append("\n");
    sb.append("    segmentStatus: ").append(toIndentedString(segmentStatus)).append("\n");
    sb.append("    killSwitchEnabled: ").append(toIndentedString(killSwitchEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
