/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Loss
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class Loss {
  @SerializedName("total")
  private Object total = null;

  @SerializedName("realised")
  private Object realised = null;

  @SerializedName("unrealised")
  private Object unrealised = null;

  public Loss total(Object total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(description = "")
  public Object getTotal() {
    return total;
  }

  public void setTotal(Object total) {
    this.total = total;
  }

  public Loss realised(Object realised) {
    this.realised = realised;
    return this;
  }

   /**
   * Get realised
   * @return realised
  **/
  @Schema(description = "")
  public Object getRealised() {
    return realised;
  }

  public void setRealised(Object realised) {
    this.realised = realised;
  }

  public Loss unrealised(Object unrealised) {
    this.unrealised = unrealised;
    return this;
  }

   /**
   * Get unrealised
   * @return unrealised
  **/
  @Schema(description = "")
  public Object getUnrealised() {
    return unrealised;
  }

  public void setUnrealised(Object unrealised) {
    this.unrealised = unrealised;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Loss loss = (Loss) o;
    return Objects.equals(this.total, loss.total) &&
        Objects.equals(this.realised, loss.realised) &&
        Objects.equals(this.unrealised, loss.unrealised);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, realised, unrealised);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Loss {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    realised: ").append(toIndentedString(realised)).append("\n");
    sb.append("    unrealised: ").append(toIndentedString(unrealised)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
