/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MarketQuoteOptionGreekV3
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-11T15:38:03.274098+05:30[Asia/Kolkata]")

public class MarketQuoteOptionGreekV3 {
  @SerializedName("last_price")
  private Double lastPrice = null;

  @SerializedName("instrument_token")
  private String instrumentToken = null;

  @SerializedName("ltq")
  private Long ltq = null;

  @SerializedName("volume")
  private Long volume = null;

  @SerializedName("cp")
  private Double cp = null;

  @SerializedName("iv")
  private Double iv = null;

  @SerializedName("vega")
  private Double vega = null;

  @SerializedName("gamma")
  private Double gamma = null;

  @SerializedName("theta")
  private Double theta = null;

  @SerializedName("delta")
  private Double delta = null;

  @SerializedName("oi")
  private Double oi = null;

  public MarketQuoteOptionGreekV3 lastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

   /**
   * Get lastPrice
   * @return lastPrice
  **/
  @Schema(description = "")
  public Double getLastPrice() {
    return lastPrice;
  }

  public void setLastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
  }

  public MarketQuoteOptionGreekV3 instrumentToken(String instrumentToken) {
    this.instrumentToken = instrumentToken;
    return this;
  }

   /**
   * Get instrumentToken
   * @return instrumentToken
  **/
  @Schema(description = "")
  public String getInstrumentToken() {
    return instrumentToken;
  }

  public void setInstrumentToken(String instrumentToken) {
    this.instrumentToken = instrumentToken;
  }

  public MarketQuoteOptionGreekV3 ltq(Long ltq) {
    this.ltq = ltq;
    return this;
  }

   /**
   * Get ltq
   * @return ltq
  **/
  @Schema(description = "")
  public Long getLtq() {
    return ltq;
  }

  public void setLtq(Long ltq) {
    this.ltq = ltq;
  }

  public MarketQuoteOptionGreekV3 volume(Long volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @Schema(description = "")
  public Long getVolume() {
    return volume;
  }

  public void setVolume(Long volume) {
    this.volume = volume;
  }

  public MarketQuoteOptionGreekV3 cp(Double cp) {
    this.cp = cp;
    return this;
  }

   /**
   * Get cp
   * @return cp
  **/
  @Schema(description = "")
  public Double getCp() {
    return cp;
  }

  public void setCp(Double cp) {
    this.cp = cp;
  }

  public MarketQuoteOptionGreekV3 iv(Double iv) {
    this.iv = iv;
    return this;
  }

   /**
   * Get iv
   * @return iv
  **/
  @Schema(description = "")
  public Double getIv() {
    return iv;
  }

  public void setIv(Double iv) {
    this.iv = iv;
  }

  public MarketQuoteOptionGreekV3 vega(Double vega) {
    this.vega = vega;
    return this;
  }

   /**
   * Get vega
   * @return vega
  **/
  @Schema(description = "")
  public Double getVega() {
    return vega;
  }

  public void setVega(Double vega) {
    this.vega = vega;
  }

  public MarketQuoteOptionGreekV3 gamma(Double gamma) {
    this.gamma = gamma;
    return this;
  }

   /**
   * Get gamma
   * @return gamma
  **/
  @Schema(description = "")
  public Double getGamma() {
    return gamma;
  }

  public void setGamma(Double gamma) {
    this.gamma = gamma;
  }

  public MarketQuoteOptionGreekV3 theta(Double theta) {
    this.theta = theta;
    return this;
  }

   /**
   * Get theta
   * @return theta
  **/
  @Schema(description = "")
  public Double getTheta() {
    return theta;
  }

  public void setTheta(Double theta) {
    this.theta = theta;
  }

  public MarketQuoteOptionGreekV3 delta(Double delta) {
    this.delta = delta;
    return this;
  }

   /**
   * Get delta
   * @return delta
  **/
  @Schema(description = "")
  public Double getDelta() {
    return delta;
  }

  public void setDelta(Double delta) {
    this.delta = delta;
  }

  public MarketQuoteOptionGreekV3 oi(Double oi) {
    this.oi = oi;
    return this;
  }

   /**
   * Get oi
   * @return oi
  **/
  @Schema(description = "")
  public Double getOi() {
    return oi;
  }

  public void setOi(Double oi) {
    this.oi = oi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketQuoteOptionGreekV3 marketQuoteOptionGreekV3 = (MarketQuoteOptionGreekV3) o;
    return Objects.equals(this.lastPrice, marketQuoteOptionGreekV3.lastPrice) &&
        Objects.equals(this.instrumentToken, marketQuoteOptionGreekV3.instrumentToken) &&
        Objects.equals(this.ltq, marketQuoteOptionGreekV3.ltq) &&
        Objects.equals(this.volume, marketQuoteOptionGreekV3.volume) &&
        Objects.equals(this.cp, marketQuoteOptionGreekV3.cp) &&
        Objects.equals(this.iv, marketQuoteOptionGreekV3.iv) &&
        Objects.equals(this.vega, marketQuoteOptionGreekV3.vega) &&
        Objects.equals(this.gamma, marketQuoteOptionGreekV3.gamma) &&
        Objects.equals(this.theta, marketQuoteOptionGreekV3.theta) &&
        Objects.equals(this.delta, marketQuoteOptionGreekV3.delta) &&
        Objects.equals(this.oi, marketQuoteOptionGreekV3.oi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastPrice, instrumentToken, ltq, volume, cp, iv, vega, gamma, theta, delta, oi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketQuoteOptionGreekV3 {\n");
    
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    instrumentToken: ").append(toIndentedString(instrumentToken)).append("\n");
    sb.append("    ltq: ").append(toIndentedString(ltq)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    cp: ").append(toIndentedString(cp)).append("\n");
    sb.append("    iv: ").append(toIndentedString(iv)).append("\n");
    sb.append("    vega: ").append(toIndentedString(vega)).append("\n");
    sb.append("    gamma: ").append(toIndentedString(gamma)).append("\n");
    sb.append("    theta: ").append(toIndentedString(theta)).append("\n");
    sb.append("    delta: ").append(toIndentedString(delta)).append("\n");
    sb.append("    oi: ").append(toIndentedString(oi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
