/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.upstox.api.OhlcV3;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MarketQuoteOHLCV3
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-05-11T15:38:03.274098+05:30[Asia/Kolkata]")

public class MarketQuoteOHLCV3 {
  @SerializedName("last_price")
  private Double lastPrice = null;

  @SerializedName("instrument_token")
  private String instrumentToken = null;

  @SerializedName("prev_ohlc")
  private OhlcV3 prevOhlc = null;

  @SerializedName("live_ohlc")
  private OhlcV3 liveOhlc = null;

   /**
   * The last traded price of symbol
   * @return lastPrice
  **/
  @Schema(example = "120.01", description = "The last traded price of symbol")
  public Double getLastPrice() {
    return lastPrice;
  }

  public MarketQuoteOHLCV3 instrumentToken(String instrumentToken) {
    this.instrumentToken = instrumentToken;
    return this;
  }

   /**
   * Get instrumentToken
   * @return instrumentToken
  **/
  @Schema(description = "")
  public String getInstrumentToken() {
    return instrumentToken;
  }

  public void setInstrumentToken(String instrumentToken) {
    this.instrumentToken = instrumentToken;
  }

  public MarketQuoteOHLCV3 prevOhlc(OhlcV3 prevOhlc) {
    this.prevOhlc = prevOhlc;
    return this;
  }

   /**
   * Get prevOhlc
   * @return prevOhlc
  **/
  @Schema(description = "")
  public OhlcV3 getPrevOhlc() {
    return prevOhlc;
  }

  public void setPrevOhlc(OhlcV3 prevOhlc) {
    this.prevOhlc = prevOhlc;
  }

  public MarketQuoteOHLCV3 liveOhlc(OhlcV3 liveOhlc) {
    this.liveOhlc = liveOhlc;
    return this;
  }

   /**
   * Get liveOhlc
   * @return liveOhlc
  **/
  @Schema(description = "")
  public OhlcV3 getLiveOhlc() {
    return liveOhlc;
  }

  public void setLiveOhlc(OhlcV3 liveOhlc) {
    this.liveOhlc = liveOhlc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketQuoteOHLCV3 marketQuoteOHLCV3 = (MarketQuoteOHLCV3) o;
    return Objects.equals(this.lastPrice, marketQuoteOHLCV3.lastPrice) &&
        Objects.equals(this.instrumentToken, marketQuoteOHLCV3.instrumentToken) &&
        Objects.equals(this.prevOhlc, marketQuoteOHLCV3.prevOhlc) &&
        Objects.equals(this.liveOhlc, marketQuoteOHLCV3.liveOhlc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastPrice, instrumentToken, prevOhlc, liveOhlc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketQuoteOHLCV3 {\n");
    
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    instrumentToken: ").append(toIndentedString(instrumentToken)).append("\n");
    sb.append("    prevOhlc: ").append(toIndentedString(prevOhlc)).append("\n");
    sb.append("    liveOhlc: ").append(toIndentedString(liveOhlc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
