/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NewsResponsePageData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-20T12:23:58.995296+05:30[Asia/Kolkata]")

public class NewsResponsePageData {
  @SerializedName("page_number")
  private Object pageNumber = null;

  @SerializedName("page_size")
  private Object pageSize = null;

  @SerializedName("total_records")
  private Object totalRecords = null;

  @SerializedName("total_pages")
  private Object totalPages = null;

  public NewsResponsePageData pageNumber(Object pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @Schema(description = "")
  public Object getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Object pageNumber) {
    this.pageNumber = pageNumber;
  }

  public NewsResponsePageData pageSize(Object pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Object getPageSize() {
    return pageSize;
  }

  public void setPageSize(Object pageSize) {
    this.pageSize = pageSize;
  }

  public NewsResponsePageData totalRecords(Object totalRecords) {
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * Get totalRecords
   * @return totalRecords
  **/
  @Schema(description = "")
  public Object getTotalRecords() {
    return totalRecords;
  }

  public void setTotalRecords(Object totalRecords) {
    this.totalRecords = totalRecords;
  }

  public NewsResponsePageData totalPages(Object totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @Schema(description = "")
  public Object getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Object totalPages) {
    this.totalPages = totalPages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewsResponsePageData newsResponsePageData = (NewsResponsePageData) o;
    return Objects.equals(this.pageNumber, newsResponsePageData.pageNumber) &&
        Objects.equals(this.pageSize, newsResponsePageData.pageSize) &&
        Objects.equals(this.totalRecords, newsResponsePageData.totalRecords) &&
        Objects.equals(this.totalPages, newsResponsePageData.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNumber, pageSize, totalRecords, totalPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewsResponsePageData {\n");
    
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
