/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PayoutDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-06-25T20:07:12.239739+05:30[Asia/Kolkata]")

public class PayoutDetails {
  @SerializedName("status")
  private Object status = null;

  @SerializedName("mode")
  private Object mode = null;

  @SerializedName("amount")
  private Object amount = null;

  @SerializedName("currency")
  private Object currency = null;

  @SerializedName("eta")
  private Object eta = null;

  @SerializedName("message")
  private Object message = null;

  @SerializedName("transaction_id")
  private Object transactionId = null;

  @SerializedName("created_at")
  private Object createdAt = null;

  @SerializedName("bank_name")
  private Object bankName = null;

  @SerializedName("transaction_fee")
  private Object transactionFee = null;

  public PayoutDetails status(Object status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }

  public PayoutDetails mode(Object mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @Schema(description = "")
  public Object getMode() {
    return mode;
  }

  public void setMode(Object mode) {
    this.mode = mode;
  }

  public PayoutDetails amount(Object amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public Object getAmount() {
    return amount;
  }

  public void setAmount(Object amount) {
    this.amount = amount;
  }

  public PayoutDetails currency(Object currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public Object getCurrency() {
    return currency;
  }

  public void setCurrency(Object currency) {
    this.currency = currency;
  }

  public PayoutDetails eta(Object eta) {
    this.eta = eta;
    return this;
  }

   /**
   * Get eta
   * @return eta
  **/
  @Schema(description = "")
  public Object getEta() {
    return eta;
  }

  public void setEta(Object eta) {
    this.eta = eta;
  }

  public PayoutDetails message(Object message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public Object getMessage() {
    return message;
  }

  public void setMessage(Object message) {
    this.message = message;
  }

  public PayoutDetails transactionId(Object transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public Object getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(Object transactionId) {
    this.transactionId = transactionId;
  }

  public PayoutDetails createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public PayoutDetails bankName(Object bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @Schema(description = "")
  public Object getBankName() {
    return bankName;
  }

  public void setBankName(Object bankName) {
    this.bankName = bankName;
  }

  public PayoutDetails transactionFee(Object transactionFee) {
    this.transactionFee = transactionFee;
    return this;
  }

   /**
   * Get transactionFee
   * @return transactionFee
  **/
  @Schema(description = "")
  public Object getTransactionFee() {
    return transactionFee;
  }

  public void setTransactionFee(Object transactionFee) {
    this.transactionFee = transactionFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutDetails payoutDetails = (PayoutDetails) o;
    return Objects.equals(this.status, payoutDetails.status) &&
        Objects.equals(this.mode, payoutDetails.mode) &&
        Objects.equals(this.amount, payoutDetails.amount) &&
        Objects.equals(this.currency, payoutDetails.currency) &&
        Objects.equals(this.eta, payoutDetails.eta) &&
        Objects.equals(this.message, payoutDetails.message) &&
        Objects.equals(this.transactionId, payoutDetails.transactionId) &&
        Objects.equals(this.createdAt, payoutDetails.createdAt) &&
        Objects.equals(this.bankName, payoutDetails.bankName) &&
        Objects.equals(this.transactionFee, payoutDetails.transactionFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, mode, amount, currency, eta, message, transactionId, createdAt, bankName, transactionFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutDetails {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    transactionFee: ").append(toIndentedString(transactionFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
