/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.upstox.api.PayoutModesData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PayoutModesResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-06-25T20:07:12.239739+05:30[Asia/Kolkata]")

public class PayoutModesResponse {
  @SerializedName("status")
  private Object status = null;

  @SerializedName("data")
  private PayoutModesData data = null;

  public PayoutModesResponse status(Object status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }

  public PayoutModesResponse data(PayoutModesData data) {
    this.data = data;
    return this;
  }

   /**
   * Available payout modes with eligibility details
   * @return data
  **/
  @Schema(description = "Available payout modes with eligibility details")
  public PayoutModesData getData() {
    return data;
  }

  public void setData(PayoutModesData data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayoutModesResponse payoutModesResponse = (PayoutModesResponse) o;
    return Objects.equals(this.status, payoutModesResponse.status) &&
        Objects.equals(this.data, payoutModesResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayoutModesResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
