/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PledgeUnavailableToTrade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class PledgeUnavailableToTrade {
  @SerializedName("equity")
  private Object equity = null;

  @SerializedName("mutual_funds")
  private Object mutualFunds = null;

  public PledgeUnavailableToTrade equity(Object equity) {
    this.equity = equity;
    return this;
  }

   /**
   * Get equity
   * @return equity
  **/
  @Schema(description = "")
  public Object getEquity() {
    return equity;
  }

  public void setEquity(Object equity) {
    this.equity = equity;
  }

  public PledgeUnavailableToTrade mutualFunds(Object mutualFunds) {
    this.mutualFunds = mutualFunds;
    return this;
  }

   /**
   * Get mutualFunds
   * @return mutualFunds
  **/
  @Schema(description = "")
  public Object getMutualFunds() {
    return mutualFunds;
  }

  public void setMutualFunds(Object mutualFunds) {
    this.mutualFunds = mutualFunds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PledgeUnavailableToTrade pledgeUnavailableToTrade = (PledgeUnavailableToTrade) o;
    return Objects.equals(this.equity, pledgeUnavailableToTrade.equity) &&
        Objects.equals(this.mutualFunds, pledgeUnavailableToTrade.mutualFunds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(equity, mutualFunds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PledgeUnavailableToTrade {\n");
    
    sb.append("    equity: ").append(toIndentedString(equity)).append("\n");
    sb.append("    mutualFunds: ").append(toIndentedString(mutualFunds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
