/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SearchPage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-03-18T13:23:00.662556+05:30[Asia/Kolkata]")

public class SearchPage {
  @SerializedName("page_number")
  private Object pageNumber = null;

  @SerializedName("total_pages")
  private Object totalPages = null;

  @SerializedName("records")
  private Object records = null;

  @SerializedName("total_records")
  private Object totalRecords = null;

  public SearchPage pageNumber(Object pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Get pageNumber
   * @return pageNumber
  **/
  @Schema(description = "")
  public Object getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Object pageNumber) {
    this.pageNumber = pageNumber;
  }

  public SearchPage totalPages(Object totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @Schema(description = "")
  public Object getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Object totalPages) {
    this.totalPages = totalPages;
  }

  public SearchPage records(Object records) {
    this.records = records;
    return this;
  }

   /**
   * Get records
   * @return records
  **/
  @Schema(description = "")
  public Object getRecords() {
    return records;
  }

  public void setRecords(Object records) {
    this.records = records;
  }

  public SearchPage totalRecords(Object totalRecords) {
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * Get totalRecords
   * @return totalRecords
  **/
  @Schema(description = "")
  public Object getTotalRecords() {
    return totalRecords;
  }

  public void setTotalRecords(Object totalRecords) {
    this.totalRecords = totalRecords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchPage searchPage = (SearchPage) o;
    return Objects.equals(this.pageNumber, searchPage.pageNumber) &&
        Objects.equals(this.totalPages, searchPage.totalPages) &&
        Objects.equals(this.records, searchPage.records) &&
        Objects.equals(this.totalRecords, searchPage.totalRecords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNumber, totalPages, records, totalRecords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchPage {\n");
    
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
