/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ShareHoldingData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-12T09:02:57.145121+05:30[Asia/Kolkata]")

public class ShareHoldingData {
  @SerializedName("category")
  private Object category = null;

  @SerializedName("history")
  private Object history = null;

   /**
   * Category of shareholder
   * @return category
  **/
  @Schema(example = "Promoters", description = "Category of shareholder")
  public Object getCategory() {
    return category;
  }

   /**
   * Quarterly shareholding history
   * @return history
  **/
  @Schema(description = "Quarterly shareholding history")
  public Object getHistory() {
    return history;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareHoldingData shareHoldingData = (ShareHoldingData) o;
    return Objects.equals(this.category, shareHoldingData.category) &&
        Objects.equals(this.history, shareHoldingData.history);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, history);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareHoldingData {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
