/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UnsettledProfit
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class UnsettledProfit {
  @SerializedName("todays_profit")
  private Object todaysProfit = null;

  @SerializedName("previous_days")
  private Object previousDays = null;

  public UnsettledProfit todaysProfit(Object todaysProfit) {
    this.todaysProfit = todaysProfit;
    return this;
  }

   /**
   * Get todaysProfit
   * @return todaysProfit
  **/
  @Schema(description = "")
  public Object getTodaysProfit() {
    return todaysProfit;
  }

  public void setTodaysProfit(Object todaysProfit) {
    this.todaysProfit = todaysProfit;
  }

  public UnsettledProfit previousDays(Object previousDays) {
    this.previousDays = previousDays;
    return this;
  }

   /**
   * Get previousDays
   * @return previousDays
  **/
  @Schema(description = "")
  public Object getPreviousDays() {
    return previousDays;
  }

  public void setPreviousDays(Object previousDays) {
    this.previousDays = previousDays;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnsettledProfit unsettledProfit = (UnsettledProfit) o;
    return Objects.equals(this.todaysProfit, unsettledProfit.todaysProfit) &&
        Objects.equals(this.previousDays, unsettledProfit.previousDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(todaysProfit, previousDays);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnsettledProfit {\n");
    
    sb.append("    todaysProfit: ").append(toIndentedString(todaysProfit)).append("\n");
    sb.append("    previousDays: ").append(toIndentedString(previousDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
