/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.upstox.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateUserIpRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-04-10T11:17:14.540672+05:30[Asia/Kolkata]")

public class UpdateUserIpRequest {
  @SerializedName("primary_ip")
  private Object primaryIp = null;

  @SerializedName("secondary_ip")
  private Object secondaryIp = null;

  public UpdateUserIpRequest primaryIp(Object primaryIp) {
    this.primaryIp = primaryIp;
    return this;
  }

   /**
   * Get primaryIp
   * @return primaryIp
  **/
  @Schema(description = "")
  public Object getPrimaryIp() {
    return primaryIp;
  }

  public void setPrimaryIp(Object primaryIp) {
    this.primaryIp = primaryIp;
  }

  public UpdateUserIpRequest secondaryIp(Object secondaryIp) {
    this.secondaryIp = secondaryIp;
    return this;
  }

   /**
   * Get secondaryIp
   * @return secondaryIp
  **/
  @Schema(description = "")
  public Object getSecondaryIp() {
    return secondaryIp;
  }

  public void setSecondaryIp(Object secondaryIp) {
    this.secondaryIp = secondaryIp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserIpRequest updateUserIpRequest = (UpdateUserIpRequest) o;
    return Objects.equals(this.primaryIp, updateUserIpRequest.primaryIp) &&
        Objects.equals(this.secondaryIp, updateUserIpRequest.secondaryIp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primaryIp, secondaryIp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserIpRequest {\n");
    
    sb.append("    primaryIp: ").append(toIndentedString(primaryIp)).append("\n");
    sb.append("    secondaryIp: ").append(toIndentedString(secondaryIp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
