package io.swagger.client.api.sdk;

public class Constant {
    public static final String accessToken = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI3UEJDNkQiLCJqdGkiOiI2NWZhN2RjMzYyNTQ1NDQzNmY1YjFhZjIiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNBY3RpdmUiOnRydWUsInNjb3BlIjpbImludGVyYWN0aXZlIiwiaGlzdG9yaWNhbCJdLCJpYXQiOjE3MTA5MTUwMTEsImlzcyI6InVkYXBpLWdhdGV3YXktc2VydmljZSIsImV4cCI6MTcxMDk3MjAwMH0.6Fefu2fUQAMbTGG_KaGksI9cyp8QsAZjPI5fX0qFoL4";
}
