/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import com.upstox.api.ApiGatewayErrorResponse;
import com.upstox.api.BalanceSheetResponse;
import com.upstox.api.CashFlowResponse;
import com.upstox.api.CompanyProfileResponse;
import com.upstox.api.CompetitorsResponse;
import com.upstox.api.CorporateActionsResponse;
import com.upstox.api.IncomeStatementResponse;
import com.upstox.api.KeyRatiosResponse;
import com.upstox.api.ShareHoldingsResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for FundamentalsApi
 */
@Ignore
public class FundamentalsApiTest {

    private final FundamentalsApi api = new FundamentalsApi();

    /**
     * Get Balance Sheet
     *
     * Fetches balance sheet data for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBalanceSheetTest() throws Exception {
        Object isin = null;
        Object type = null;
        Object fs = null;
        BalanceSheetResponse response = api.getBalanceSheet(isin, type, fs);

        // TODO: test validations
    }
    /**
     * Get Cash Flow
     *
     * Fetches cash flow data for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCashFlowTest() throws Exception {
        Object isin = null;
        Object type = null;
        Object fs = null;
        CashFlowResponse response = api.getCashFlow(isin, type, fs);

        // TODO: test validations
    }
    /**
     * Get Company Profile
     *
     * Fetches company profile information for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCompanyProfileTest() throws Exception {
        Object isin = null;
        CompanyProfileResponse response = api.getCompanyProfile(isin);

        // TODO: test validations
    }
    /**
     * Get Competitors
     *
     * Fetches the list of competitors for the given instrument_key.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCompetitorsTest() throws Exception {
        Object instrumentKey = null;
        CompetitorsResponse response = api.getCompetitors(instrumentKey);

        // TODO: test validations
    }
    /**
     * Get Corporate Actions
     *
     * Fetches corporate actions for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCorporateActionsTest() throws Exception {
        Object isin = null;
        CorporateActionsResponse response = api.getCorporateActions(isin);

        // TODO: test validations
    }
    /**
     * Get Income Statement
     *
     * Fetches income statement data for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getIncomeStatementTest() throws Exception {
        Object isin = null;
        Object type = null;
        Object timePeriod = null;
        Object fs = null;
        IncomeStatementResponse response = api.getIncomeStatement(isin, type, timePeriod, fs);

        // TODO: test validations
    }
    /**
     * Get Key Ratios
     *
     * Fetches key financial ratios for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getKeyRatiosTest() throws Exception {
        Object isin = null;
        KeyRatiosResponse response = api.getKeyRatios(isin);

        // TODO: test validations
    }
    /**
     * Get Share Holdings
     *
     * Fetches shareholding pattern for the given ISIN.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getShareHoldingsTest() throws Exception {
        Object isin = null;
        ShareHoldingsResponse response = api.getShareHoldings(isin);

        // TODO: test validations
    }
}
