/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import com.upstox.api.ApiGatewayErrorResponse;
import com.upstox.api.SearchInstrumentResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for InstrumentsApi
 */
@Ignore
public class InstrumentsApiTest {

    private final InstrumentsApi api = new InstrumentsApi();

    /**
     * Search instruments
     *
     * This API provides the functionality to retrieve the instrument details for searched query
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchInstrumentTest() throws Exception {
        Object query = null;
        Object exchanges = null;
        Object segments = null;
        Object instrumentTypes = null;
        Object expiry = null;
        Object atmOffset = null;
        Object pageNumber = null;
        Object records = null;
        SearchInstrumentResponse response = api.searchInstrument(query, exchanges, segments, instrumentTypes, expiry, atmOffset, pageNumber, records);

        // TODO: test validations
    }
}
