/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import com.upstox.api.ApiGatewayErrorResponse;
import com.upstox.api.GetOptionChainResponse;
import com.upstox.api.GetOptionContractResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OptionsApi
 */
@Ignore
public class OptionsApiTest {

    private final OptionsApi api = new OptionsApi();

    /**
     * Get option contracts
     *
     * This API provides the functionality to retrieve the option contracts
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOptionContractsTest() throws Exception {
        String instrumentKey = null;
        String expiryDate = null;
        GetOptionContractResponse response = api.getOptionContracts(instrumentKey, expiryDate);

        // TODO: test validations
    }
    /**
     * Get option chain
     *
     * This API provides the functionality to retrieve the option chain
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getPutCallOptionChainTest() throws Exception {
        String instrumentKey = null;
        String expiryDate = null;
        GetOptionChainResponse response = api.getPutCallOptionChain(instrumentKey, expiryDate);

        // TODO: test validations
    }
}
