/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import com.upstox.api.ApiGatewayErrorResponse;
import com.upstox.api.TradeHistoryResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PostTradeApi
 */
@Ignore
public class PostTradeApiTest {

    private final PostTradeApi api = new PostTradeApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTradesByDateRange() throws Exception {
        String startDate = null;
        String endDate = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        String segment = null;
        TradeHistoryResponse response = api.getTradesByDateRange(startDate, endDate, pageNumber, pageSize, segment);

        // TODO: test validations
    }
}
